PENG-1551 - Create charm-jobbergate-agent
omnivector-solutions/charm-jobbergate-agent pull request #1
Opened 2023-08-23 21:49 UTC by fschuch

Create a new charm for deploying the new `jobbergate-agent`. It should be almost identical to the cluster-agent 

Notice the `main` branch contains the code copied from cluster-agent, so this PR highlights just the changes to make it `jobbergate-agent`.

`Task`: https://app.clickup.com/t/18022949/PENG-1552

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2023-08-24 13:04 UTC, jaimesouza requested changes

2023-08-24 13:04 UTC, jaimesouza commented on src/charm.py
>  class ClusterAgentCharm(CharmBase):
I think this class should be renamed.

2023-08-24 13:04 UTC, jaimesouza commented on src/charm.py
> -        self.cluster_agent_ops = ClusterAgentOps(self)
`ClusterAgentOps` should be` JobbergateAgentOps` also.

2023-08-24 13:04 UTC, jaimesouza commented on src/cluster_agent_ops.py
>  class ClusterAgentOps:
It should be` JobbergateAgentOps`.

2023-08-28 14:27 UTC, fschuch commented on src/cluster_agent_ops.py
>  class ClusterAgentOps:
solved in [ed479f6](https://github.com/omnivector-solutions/charm-jobbergate-agent/pull/1/commits/ed479f611c10625ed31eccf03fa680731684f725)

2023-08-28 14:27 UTC, fschuch commented on src/charm.py
> -        self.cluster_agent_ops = ClusterAgentOps(self)
solved in [ed479f6](https://github.com/omnivector-solutions/charm-jobbergate-agent/pull/1/commits/ed479f611c10625ed31eccf03fa680731684f725)

2023-08-28 21:58 UTC, merged